CREATE USER IF NOT EXISTS 'crmuser'@'%' IDENTIFIED BY 'crmpassword';
CREATE DATABASE IF NOT EXISTS crm DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_bin;
GRANT ALL PRIVILEGES ON crm.* TO 'crmuser'@'%' IDENTIFIED BY 'crmpassword';
GRANT GRANT OPTION ON crm.* TO 'crmuser'@'%' IDENTIFIED BY 'crmpassword';
FLUSH PRIVILEGES;